// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb0y56XQeR8gaz9fOR5WJFsnEFM1dQ0BE',
    appId: '1:807112993038:web:3ed3e136ebd18655a60f5f',
    messagingSenderId: '807112993038',
    projectId: 'healthlogger-application',
    authDomain: 'healthlogger-application.firebaseapp.com',
    storageBucket: 'healthlogger-application.appspot.com',
    measurementId: 'G-JSRHMY5KKD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDT0Gz5gcuSml0S4YvVt10u0tjcMW5yJMc',
    appId: '1:807112993038:android:566ad3964506ae90a60f5f',
    messagingSenderId: '807112993038',
    projectId: 'healthlogger-application',
    storageBucket: 'healthlogger-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuhd6jhQG6Jor6Fu0f6uNAn0jFq3ke5N8',
    appId: '1:807112993038:ios:db269b06120b5fcaa60f5f',
    messagingSenderId: '807112993038',
    projectId: 'healthlogger-application',
    storageBucket: 'healthlogger-application.appspot.com',
    iosBundleId: 'com.example.application',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuhd6jhQG6Jor6Fu0f6uNAn0jFq3ke5N8',
    appId: '1:807112993038:ios:a349ce68d976c714a60f5f',
    messagingSenderId: '807112993038',
    projectId: 'healthlogger-application',
    storageBucket: 'healthlogger-application.appspot.com',
    iosBundleId: 'com.example.application.RunnerTests',
  );
}
